### ISSUE TITLE
User Based Raids

### ISSUE THREAD

**Issue by The-Real-Ketchum-Dev** [IZODI/rkhouseCSPM#3]
I was thinking there may be some that have done the command -cd in there database for whatever reason. Is there a way to make it completely based on users? In other words kinda like meowth does where you can post a raid with a command and it automatically works it into the channel. Instead we can do a command something like ^raid 'gym-name' <lat> <lng> and ^egg 'gym-name' <lat> <lng>

**Comment by smbambling** [comment]
Seems to me like these tools have different functions, why not just use Meowth for the other function.

**Comment by The-Real-Ketchum-Dev** [comment]
Because adding the other bot doesnt post it to the map instead puts it in discord. I just thought having a feature like so would help users and not just discord users
